In [12]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Listen.csv')

In [6]:
df.head(3)

,Timestamp,Age,Primary streaming service,Hours per day,While working,Instrumentalist,Composer,Fav genre,Exploratory,Foreign languages,...,Frequency [R&B],Frequency [Rap],Frequency [Rock],Frequency [Video game music],Anxiety,Depression,Insomnia,OCD,Music effects,Permissions
0,8/27/2022 19:29:02,18.0,Spotify,3.0,Yes,Yes,Yes,Latin,Yes,Yes,...,Sometimes,Very frequently,Never,Sometimes,3.0,0.0,1.0,0.0,NaN,I understand.
1,8/27/2022 19:57:31,63.0,Pandora,1.5,Yes,No,No,Rock,Yes,No,...,Sometimes,Rarely,Very frequently,Rarely,7.0,2.0,2.0,1.0,NaN,I understand.
2,8/27/2022 21:28:18,18.0,Spotify,4.0,No,No,No,Video game music,No,Yes,...,Never,Rarely,Rarely,Very frequently,7.0,7.0,10.0,2.0,No effect,I understand.

In [7]:
df.tail(4)

,Timestamp,Age,Primary streaming service,Hours per day,While working,Instrumentalist,Composer,Fav genre,Exploratory,Foreign languages,...,Frequency [R&B],Frequency [Rap],Frequency [Rock],Frequency [Video game music],Anxiety,Depression,Insomnia,OCD,Music effects,Permissions
732,11/1/2022 22:26:42,18.0,Spotify,1.0,Yes,Yes,No,Pop,Yes,Yes,...,Never,Never,Sometimes,Sometimes,3.0,2.0,2.0,5.0,Improve,I understand.
733,11/3/2022 23:24:38,19.0,Other streaming service,6.0,Yes,No,Yes,Rap,Yes,No,...,Sometimes,Sometimes,Rarely,Rarely,2.0,2.0,2.0,2.0,Improve,I understand.
734,11/4/2022 17:31:47,19.0,Spotify,5.0,Yes,Yes,No,Classical,No,No,...,Never,Never,Never,Sometimes,2.0,3.0,2.0,1.0,Improve,I understand.
735,11/9/2022 1:55:20,29.0,YouTube Music,2.0,Yes,No,No,Hip hop,Yes,Yes,...,Very frequently,Very frequently,Very frequently,Rarely,2.0,2.0,2.0,5.0,Improve,I understand.

In [8]:
df.columns

Index(['Timestamp', 'Age', 'Primary streaming service', 'Hours per day',
       'While working', 'Instrumentalist', 'Composer', 'Fav genre',
       'Exploratory', 'Foreign languages', 'BPM', 'Frequency [Classical]',
       'Frequency [Country]', 'Frequency [EDM]', 'Frequency [Folk]',
       'Frequency [Gospel]', 'Frequency [Hip hop]', 'Frequency [Jazz]',
       'Frequency [K pop]', 'Frequency [Latin]', 'Frequency [Lofi]',
       'Frequency [Metal]', 'Frequency [Pop]', 'Frequency [R&B]',
       'Frequency [Rap]', 'Frequency [Rock]', 'Frequency [Video game music]',
       'Anxiety', 'Depression', 'Insomnia', 'OCD', 'Music effects',
       'Permissions'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 736 entries, 0 to 735
Data columns (total 33 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Timestamp                     736 non-null    object
 1   Age                           735 non-null    float64
 2   Primary streaming service     735 non-null    object
 3   Hours per day                 736 non-null    float64
 4   While working                 733 non-null    object
 5   Instrumentalist               732 non-null    object
 6   Composer                      735 non-null    object
 7   Fav genre                     736 non-null    object
 8   Exploratory                   736 non-null    object
 9   Foreign languages             732 non-null    object
 10  BPM                           629 non-null    float64
 11  Frequency [Classical]         736 non-null    object
 12  Frequency [Country]           736 non-null    object
 13  Frequency [EDM]               736 non-null    object
 14  Frequency [Folk]              736 non-null    object
 15  Frequency [Gospel]            736 non-null    object
 16  Frequency [Hip hop]           736 non-null    object
 17  Frequency [Jazz]              736 non-null    object
 18  Frequency [K pop]             736 non-null    object
 19  Frequency [Latin]             736 non-null    object
 20  Frequency [Lofi]              736 non-null    object
 21  Frequency [Metal]             736 non-null    object
 22  Frequency [Pop]               736 non-null    object
 23  Frequency [R&B]               736 non-null    object
 24  Frequency [Rap]               736 non-null    object
 25  Frequency [Rock]              736 non-null    object
 26  Frequency [Video game music]  736 non-null    object
 27  Anxiety                       736 non-null    float64
 28  Depression                    736 non-null    float64
 29  Insomnia                      736 non-null    float64
 30  OCD                           736 non-null    float64
 31  Music effects                 728 non-null    object
 32  Permissions                   736 non-null    object
dtypes: float64(7), object(26)
memory usage: 189.9+ KB

In [10]:
df.describe()

,Age,Hours per day,BPM,Anxiety,Depression,Insomnia,OCD
count,735.000000,736.000000,6.290000e+02,736.000000,736.000000,736.000000,736.000000
mean,25.206803,3.572758,1.589948e+06,5.837636,4.796196,3.738451,2.637228
std,12.054970,3.028199,3.987261e+07,2.793054,3.028870,3.088689,2.842017
min,10.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,18.000000,2.000000,1.000000e+02,4.000000,2.000000,1.000000,0.000000
50%,21.000000,3.000000,1.200000e+02,6.000000,5.000000,3.000000,2.000000
75%,28.000000,5.000000,1.440000e+02,8.000000,7.000000,6.000000,5.000000
max,89.000000,24.000000,1.000000e+09,10.000000,10.000000,10.000000,10.000000

In [11]:
df.tail()

,Timestamp,Age,Primary streaming service,Hours per day,While working,Instrumentalist,Composer,Fav genre,Exploratory,Foreign languages,...,Frequency [R&B],Frequency [Rap],Frequency [Rock],Frequency [Video game music],Anxiety,Depression,Insomnia,OCD,Music effects,Permissions
731,10/30/2022 14:37:28,17.0,Spotify,2.0,Yes,Yes,No,Rock,Yes,Yes,...,Never,Rarely,Very frequently,Never,7.0,6.0,0.0,9.0,Improve,I understand.
732,11/1/2022 22:26:42,18.0,Spotify,1.0,Yes,Yes,No,Pop,Yes,Yes,...,Never,Never,Sometimes,Sometimes,3.0,2.0,2.0,5.0,Improve,I understand.
733,11/3/2022 23:24:38,19.0,Other streaming service,6.0,Yes,No,Yes,Rap,Yes,No,...,Sometimes,Sometimes,Rarely,Rarely,2.0,2.0,2.0,2.0,Improve,I understand.
734,11/4/2022 17:31:47,19.0,Spotify,5.0,Yes,Yes,No,Classical,No,No,...,Never,Never,Never,Sometimes,2.0,3.0,2.0,1.0,Improve,I understand.
735,11/9/2022 1:55:20,29.0,YouTube Music,2.0,Yes,No,No,Hip hop,Yes,Yes,...,Very frequently,Very frequently,Very frequently,Rarely,2.0,2.0,2.0,5.0,Improve,I understand.

In [15]:
df.loc[df['BPM'] == 'null', 'BPM'] = 0

In [16]:
df.describe()

,Age,Hours per day,BPM,Anxiety,Depression,Insomnia,OCD
count,735.000000,736.000000,6.290000e+02,736.000000,736.000000,736.000000,736.000000
mean,25.206803,3.572758,1.589948e+06,5.837636,4.796196,3.738451,2.637228
std,12.054970,3.028199,3.987261e+07,2.793054,3.028870,3.088689,2.842017
min,10.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,18.000000,2.000000,1.000000e+02,4.000000,2.000000,1.000000,0.000000
50%,21.000000,3.000000,1.200000e+02,6.000000,5.000000,3.000000,2.000000
75%,28.000000,5.000000,1.440000e+02,8.000000,7.000000,6.000000,5.000000
max,89.000000,24.000000,1.000000e+09,10.000000,10.000000,10.000000,10.000000

In [24]:
df[['BPM']] == 0

       BPM
0    False
1    False
2    False
3    False
4    False
..     ...
731  False
732  False
733  False
734  False
735  False

[736 rows x 1 columns]

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 736 entries, 0 to 735
Data columns (total 33 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Timestamp                     736 non-null    object
 1   Age                           735 non-null    float64
 2   Primary streaming service     735 non-null    object
 3   Hours per day                 736 non-null    float64
 4   While working                 733 non-null    object
 5   Instrumentalist               732 non-null    object
 6   Composer                      735 non-null    object
 7   Fav genre                     736 non-null    object
 8   Exploratory                   736 non-null    object
 9   Foreign languages             732 non-null    object
 10  BPM                           736 non-null    object
 11  Frequency [Classical]         736 non-null    object
 12  Frequency [Country]           736 non-null    object
 13  Frequency [EDM]               736 non-null    object
 14  Frequency [Folk]              736 non-null    object
 15  Frequency [Gospel]            736 non-null    object
 16  Frequency [Hip hop]           736 non-null    object
 17  Frequency [Jazz]              736 non-null    object
 18  Frequency [K pop]             736 non-null    object
 19  Frequency [Latin]             736 non-null    object
 20  Frequency [Lofi]              736 non-null    object
 21  Frequency [Metal]             736 non-null    object
 22  Frequency [Pop]               736 non-null    object
 23  Frequency [R&B]               736 non-null    object
 24  Frequency [Rap]               736 non-null    object
 25  Frequency [Rock]              736 non-null    object
 26  Frequency [Video game music]  736 non-null    object
 27  Anxiety                       736 non-null    float64
 28  Depression                    736 non-null    float64
 29  Insomnia                      736 non-null    float64
 30  OCD                           736 non-null    float64
 31  Music effects                 728 non-null    object
 32  Permissions                   736 non-null    object
dtypes: float64(6), object(27)
memory usage: 189.9+ KB